// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: crud.sql

package data

import (
	"context"
)

const listAccountGroups = `-- name: ListAccountGroups :many
SELECT uuid, display_name, country, locality, postal_code, street_address, region, external_id, active, created_at, search FROM account_groups
ORDER BY display_name
`

func (q *Queries) ListAccountGroups(ctx context.Context) ([]AccountGroup, error) {
	rows, err := q.db.QueryContext(ctx, listAccountGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountGroup
	for rows.Next() {
		var i AccountGroup
		if err := rows.Scan(
			&i.Uuid,
			&i.DisplayName,
			&i.Country,
			&i.Locality,
			&i.PostalCode,
			&i.StreetAddress,
			&i.Region,
			&i.ExternalID,
			&i.Active,
			&i.CreatedAt,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
