// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AccountGroup struct {
	Uuid          uuid.UUID      `json:"uuid"`
	DisplayName   string         `json:"display_name"`
	Country       string         `json:"country"`
	Locality      string         `json:"locality"`
	PostalCode    sql.NullString `json:"postal_code"`
	StreetAddress string         `json:"street_address"`
	Region        string         `json:"region"`
	ExternalID    string         `json:"external_id"`
	Active        bool           `json:"active"`
	CreatedAt     time.Time      `json:"created_at"`
	Search        interface{}    `json:"search"`
}
